# Generated by Django 2.1.1 on 2018-12-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181209_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countries',
        ),
    ]
