# Generated by Django 2.1.1 on 2018-12-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews'), ('Afghanistan', 'Afghanistan'), ('Åland Islands', 'Åland Islands'), ('Albania', 'Albania')], max_length=50, null=True),
        ),
    ]
