# Generated by Django 2.1.1 on 2019-01-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_citizenshipcountries'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenshipcountries',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
